import type { FastifyInstance } from 'fastify';
import type { DB } from '../db.js';
import type { Config } from '../config.js';
import { Errors } from '../errors.js';
import { verifyAssetSignature } from '../lib/assets.js';
import { createStorage } from '../services/storage.js';

export function registerAssetRoutes(app: FastifyInstance, db: DB, cfg: Config) {
  const storage = createStorage({
    driver: cfg.storageDriver,
    uploadsDir: cfg.uploadsDir,
    supabaseUrl: cfg.supabaseUrl,
    supabaseSecretKey: cfg.supabaseSecretKey,
    supabaseStorageBucket: cfg.supabaseStorageBucket,
  });

  // Signed URLs let normal <img> requests load private objects without exposing a Supabase key.
  // The UUID, expiry and signature are generated by the Gateway when content leaves the API.
  app.get('/v1/content/assets/:id', async (req, reply) => {
    const id = (req.params as { id: string }).id;
    const q = req.query as { expires?: string; signature?: string };
    if (!verifyAssetSignature(id, q.expires, q.signature, cfg.hmacSecret)) throw Errors.unauthorized('Invalid or expired asset URL');
    const r = await db.query('select storage_key, mime_type, checksum_sha256 from ccat.content_assets where id=$1', [id]);
    if (r.rows.length === 0) throw Errors.notFound('Asset not found');
    const obj = await storage.get(r.rows[0]!.storage_key);
    if (!obj) throw Errors.notFound('Asset bytes missing');
    reply.header('content-type', r.rows[0]!.mime_type);
    reply.header('cache-control', 'private, max-age=3600, immutable');
    reply.header('etag', `"${r.rows[0]!.checksum_sha256}"`);
    return reply.send(obj.bytes);
  });
}
